---
name: Build Static Content
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  markdown-lint:
    name: Lint markdown files
    uses: stuttgart-things/stuttgart-things/.github/workflows/lint-markdown.yaml@main
    with:
      environment-name: k8s
      runs-on: arc-runner-scale-set-blog
      continue-error: true
      alpine-version: 3.19.0
      lintprofile-path: .markdownlint.rb
      artifact-name: md-lint
